name: CI output design

# ToDos:
# - artifact upload ERC/DRC

# Controls when the action will run. Triggers the workflow on push or pull request
# events that happen on all branches
on:
  push:
    # branches: [ main ]
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kiplot.yaml'
      - '.github/workflows/generate_output.yml'
      - 'project.properties'

  pull_request:
    # branches: [ main ]
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kiplot.yaml'
      - '.github/workflows/generate_output.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  call-workflow-passing-data:
    uses: 42CrMo4/KiCad_Workflows/.github/workflows/generate_output.yml@v6.0
