name: Release Design

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'

  pull_request:
    tags:
      - 'v[0-9]+.[0-9]+'

# ToDo:
# - if any version number is over 9 then no release is in github only the tag. 
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-workflow-passing-data:
    uses: 42CrMo4/KiCad_Workflows/.github/workflows/release.yml@v6.0